### ISSUE TITLE
inquiry :compiled version for windows + combine

### ISSUE THREAD

**Issue by charulix** [Genivia/ugrep-indexer#4]
Hi,

Would there be a compiled binary version for windows for ugrep-indexer?

Will ugrep-indexer be combined with ugrep in near future?

Thanks

**Comment by genivia-inc** [comment]
This project will continue soon with updates. I'm figuring some things out in the meantime how to make it better, besides adding a windows exe version and adding the ability to index zip/tar archives and compressed files which are on the priority list.

As you know, indexed search is integrated in ugrep, but not the ability to index a FS. That is done with ugrep-indexer, which should be a separate tool and not be part of the ugrep tool.

I don't know if you perhaps mean if ugrep-indexer will eventually be part of the ugrep project? That can be done I suppose, once it comes out of beta of course.

**Comment by charulix** [comment]
thank you

**Comment by genivia-inc** [comment]
Working on an update this week that includes compressed file indexing and a Windows exe version of the indexer. The ugrep.exe will be updated later to include indexed searching on Windows.

**Comment by charulix** [comment]
thank you so much for the update

**Comment by genivia-inc** [comment]
Made time available this week to implement the exe version of the indexer and also added zip/compressed file indexing. It is working, with some caveats that I have to address.

Then my dev Windows machine died yesterday morning. Looks like a bad SSD.

Will work on this again when a replacement machine arrives. Setting up my dev env on other machines in the office is not an option right now.

**Comment by genivia-inc** [comment]
I've ugrep-indexer.exe committed to the repo with new options `-z` and `--zmax=NUM` to index archives and compressed files. Will perform some more testing tomorrow and if all goes well will then release the ugrep-indexer 0.9.2 update as a release.

The ugrep 4.3.5 update will also released and supports option `--index` with `-z` to search indexed archives and compressed files. The ugrep.exe 4.3.5 also supports indexed-based searching. Because searching zip archives and compressed files is typically slow (relatively speaking), indexing these files gives a decent speed boost.

**Comment by charulix** [comment]
Awesome, thanks for the update!

**Comment by genivia-inc** [comment]
Ugrep v4.3.5 is released with a new ugrep.exe `--index` option. Also archives and compressed files can be indexed with option `-z`.

**Comment by charulix** [comment]
thank you
